import {
  Anchor,
  ArrowRight,
  ArrowUpRight,
  AtSign,
  Award,
  BadgeCheck,
  Banknote,
  Bell,
  Bike,
  Binary,
  Book,
  BookOpen,
  Bookmark,
  Braces,
  Briefcase,
  Bug,
  Building,
  Building2,
  Calendar,
  Camera,
  Car,
  ChartColumn,
  ChartPie,
  Check,
  CheckCheck,
  ChevronRight,
  Circle,
  CircleAlert,
  CircleCheck,
  CircleUser,
  Clipboard,
  Clock,
  Cloud,
  Code,
  CodeXml,
  Cog,
  Coins,
  Compass,
  Contact,
  Cpu,
  CreditCard,
  Crown,
  Database,
  Diamond,
  DollarSign,
  Download,
  Droplet,
  ExternalLink,
  Eye,
  EyeOff,
  Feather,
  FileText,
  Film,
  Filter,
  Fingerprint,
  Flag,
  Flame,
  Flower,
  Folder,
  Gem,
  Gift,
  GitBranch,
  Globe,
  Hammer,
  Handshake,
  Headphones,
  Headset,
  Heart,
  Hexagon,
  House,
  Image,
  Inbox,
  Infinity,
  Key,
  KeyRound,
  Laptop,
  Layers,
  LayoutGrid,
  Leaf,
  Lightbulb,
  Link,
  List,
  Lock,
  LockOpen,
  Mail,
  Map,
  MapPin,
  Medal,
  Megaphone,
  Menu,
  MessageCircle,
  MessageSquare,
  Mic,
  Minus,
  Monitor,
  Moon,
  Mountain,
  Music,
  Navigation,
  Network,
  OctagonAlert,
  Package,
  Paintbrush,
  Palette,
  PenTool,
  Pencil,
  Percent,
  Phone,
  PhoneCall,
  Plane,
  Play,
  Plus,
  Power,
  Receipt,
  Rocket,
  Ruler,
  ScanFace,
  Scissors,
  Search,
  Send,
  Server,
  Settings,
  Share2,
  Shield,
  ShieldAlert,
  ShieldBan,
  ShieldCheck,
  ShieldHalf,
  Ship,
  ShoppingBag,
  ShoppingCart,
  Siren,
  Smartphone,
  Smile,
  Snowflake,
  Sparkles,
  Sprout,
  Square,
  Star,
  Store,
  Sun,
  Tag,
  Tags,
  Target,
  Terminal,
  ThumbsUp,
  TreePine,
  TrendingUp,
  Triangle,
  Trophy,
  Truck,
  Upload,
  User,
  UserCheck,
  UserPlus,
  Users,
  Video,
  Wallet,
  WandSparkles,
  Webhook,
  Wifi,
  Wrench,
  Zap,
  type LucideIcon,
} from "lucide-react";

/**
 * CMS-selectable icon set (Lucide). 164 popular icons.
 * Every key here appears in the admin icon gallery automatically. All render
 * as \`currentColor\` strokes, so they inherit text color.
 */
export const ICON_MAP: Record<string, LucideIcon> = {
  line: Minus,
  shield: Shield,
  "shield-check": ShieldCheck,
  "shield-alert": ShieldAlert,
  "shield-ban": ShieldBan,
  "shield-half": ShieldHalf,
  lock: Lock,
  "lock-open": LockOpen,
  key: Key,
  "key-round": KeyRound,
  fingerprint: Fingerprint,
  "scan-face": ScanFace,
  eye: Eye,
  "eye-off": EyeOff,
  bug: Bug,
  "user-check": UserCheck,
  "badge-check": BadgeCheck,
  siren: Siren,
  "circle-alert": CircleAlert,
  "octagon-alert": OctagonAlert,
  code: Code,
  "code-xml": CodeXml,
  terminal: Terminal,
  globe: Globe,
  server: Server,
  database: Database,
  cloud: Cloud,
  cpu: Cpu,
  wifi: Wifi,
  "git-branch": GitBranch,
  braces: Braces,
  binary: Binary,
  monitor: Monitor,
  smartphone: Smartphone,
  laptop: Laptop,
  webhook: Webhook,
  network: Network,
  "shopping-cart": ShoppingCart,
  "shopping-bag": ShoppingBag,
  "credit-card": CreditCard,
  "dollar-sign": DollarSign,
  briefcase: Briefcase,
  building: Building,
  "building-2": Building2,
  "trending-up": TrendingUp,
  "chart-column": ChartColumn,
  "chart-pie": ChartPie,
  wallet: Wallet,
  receipt: Receipt,
  tag: Tag,
  tags: Tags,
  percent: Percent,
  gift: Gift,
  coins: Coins,
  banknote: Banknote,
  handshake: Handshake,
  store: Store,
  package: Package,
  star: Star,
  heart: Heart,
  check: Check,
  "check-check": CheckCheck,
  "circle-check": CircleCheck,
  zap: Zap,
  bolt: Zap,
  sparkles: Sparkles,
  flame: Flame,
  rocket: Rocket,
  target: Target,
  award: Award,
  trophy: Trophy,
  crown: Crown,
  medal: Medal,
  "thumbs-up": ThumbsUp,
  bookmark: Bookmark,
  flag: Flag,
  bell: Bell,
  megaphone: Megaphone,
  gem: Gem,
  diamond: Diamond,
  mail: Mail,
  "message-circle": MessageCircle,
  "message-square": MessageSquare,
  phone: Phone,
  send: Send,
  "at-sign": AtSign,
  "phone-call": PhoneCall,
  video: Video,
  headset: Headset,
  inbox: Inbox,
  user: User,
  users: Users,
  "user-plus": UserPlus,
  contact: Contact,
  smile: Smile,
  "circle-user": CircleUser,
  lightbulb: Lightbulb,
  wrench: Wrench,
  settings: Settings,
  cog: Cog,
  hammer: Hammer,
  "wand-sparkles": WandSparkles,
  "pen-tool": PenTool,
  palette: Palette,
  paintbrush: Paintbrush,
  camera: Camera,
  image: Image,
  film: Film,
  music: Music,
  headphones: Headphones,
  mic: Mic,
  book: Book,
  "book-open": BookOpen,
  "file-text": FileText,
  folder: Folder,
  clipboard: Clipboard,
  pencil: Pencil,
  ruler: Ruler,
  scissors: Scissors,
  layers: Layers,
  calendar: Calendar,
  clock: Clock,
  "map-pin": MapPin,
  map: Map,
  compass: Compass,
  navigation: Navigation,
  house: House,
  plane: Plane,
  car: Car,
  truck: Truck,
  bike: Bike,
  ship: Ship,
  leaf: Leaf,
  sun: Sun,
  moon: Moon,
  snowflake: Snowflake,
  droplet: Droplet,
  mountain: Mountain,
  "tree-pine": TreePine,
  sprout: Sprout,
  flower: Flower,
  feather: Feather,
  anchor: Anchor,
  hexagon: Hexagon,
  circle: Circle,
  square: Square,
  triangle: Triangle,
  infinity: Infinity,
  "arrow-right": ArrowRight,
  "arrow-up-right": ArrowUpRight,
  "chevron-right": ChevronRight,
  plus: Plus,
  play: Play,
  power: Power,
  download: Download,
  upload: Upload,
  link: Link,
  "external-link": ExternalLink,
  share: Share2,
  search: Search,
  filter: Filter,
  "layout-grid": LayoutGrid,
  list: List,
  menu: Menu,
};

export const ICON_KEYS = Object.keys(ICON_MAP);

/** Render a named icon (defaults to shield). \`name="none"\` renders nothing. */
export function CmsIcon({
  name,
  className,
}: {
  name?: string | null;
  className?: string;
}) {
  if (name === "none") return null;
  const Icon = (name && ICON_MAP[name]) || Shield;
  return <Icon className={className} aria-hidden />;
}
